#Realm of the Fallen re:Coded;
#Libraries;
import time;
import os;
import platform;
#Variables;
username1 = 'NULL';
password1 = 'NULL';
#Boot Screen;
def entergame():
    os.system('cls');
    print('What would you like to do?');
    print();
    print('1) Create Account');
    print('2) Login');
    print('4) Exit');
    print();
    print();
    print('Current Version: v0.01alpha');
    try:
        x = int(input());
        if x == 1:
            createuser();
        elif x == 2:
            login();
        elif x == 3:
            print('Null');
            entergame();
        elif x == 4:
            os.system('cls');
            exit();
        else:
            entergame();
    except ValueError:
        entergame();
#Username Create;
def createuser():
    global username1;
    os.system('cls');
    print('What would you like you username to be?');
    username1 = str(input());
    checkforspaces()
#Checks Username For Spaces;
def checkforspaces():
    global password1;
    if ' ' in username1:
        print("Sorry, you can't use spaces in your username.");
        time.sleep(1.5);
        createuser();
#Creates Password;
    else:
        print();
        print('What would you like your password to be?');
        password1 = str(input());
        DATA_VALUES();
#Login Work on later;
def login():
    os.system('cls');
#Creates Save;
def DATA_VALUES():
    global acc1g;
    global acc1m;
    global acc2g;
    global acc2m;
    global acc3g;
    global acc3m;
    global acc4g;
    global acc4m;
    global acc5g;
    global acc5m;
    global cost;
    global cost1;
    global gcho;
    global echo;
    global e2cho;
    global e1;
    global dmgnpc;
    global ls1;
    global killcount;
    global ls2;
    global la1;
    global la2;
    global hp;
    global orighp;
    global armtype;
    global swordtype;
    global skind;
    global buyword1;
    global buyword2;
    global curlvl;
    global aan;
    global bankgold;
    global destination;
    global destination2;
    global swordchoice;
    global swordchoice2;
    global swordchoice3;
    global swordexist;
    global sprice;
    global armchoice;
    global armchoice;
    global aprice;
    global playerxp;
    global xpuntil;
    global origxp;
    global money;
    global key;
    global damage;
    global dr;
    global gmail;
    global hbone;
    global dhide;
    global rtab;
    global food;
    global rfood;
    global bait;
    global ea;
    global potion;
    global ingot;
    global seed;
    global bow;
    global fur;
    global gem;
    global log;
    global ore;
    global morb;
    global arm1;
    global arm2;
    global arm3;
    global arm4;
    global arm5;
    global arm6;
    global arm7;
    global arm8;
    global arm9;
    global arm10;
    global arm11;
    global arm12;
    global ma1;
    global ma2;
    global ma3;
    global ma4;
    global ma5;
    global ma6;
    global ma7;
    global ma8;
    global ma9;
    global ma10;
    global ms1;
    global ms2;
    global ms3;
    global ms4;
    global ms5;
    global ms6;
    global ms7;
    global ms8;
    global ms9;
    global ms10;
    global sword1;
    global sword2;
    global sword3;
    global sword4;
    global sword5;
    global sword6;
    global sword7;
    global sword8;
    global sword9;
    global sword10;
    global sword11;
    global sword12;
    global axxx;
    global pgmail;
    global phbone;
    global pdhide;
    global prtab;
    global ppotion;
    global pfood;
    global pingot;
    global pseed;
    global prfood;
    global pbait;
    global pfur;
    global pore;
    global plog;
    global pgem;
    global pbow;
    global pmorb;
    global Woodcuttinglvl;
    global Woodcuttingxpremain;
    global Woodcuttingxpgain;
    global Woodcuttingcurxp;
    global Woodcuttingxpleft;
    global Cooklvl;
    global Cookxpremain;
    global Cookxpgain;
    global Cookcurxp;
    global Cookxpleft;
    global Fishinglvl;
    global Fishingxpremain;
    global Fishingxpgain;
    global Fishingcurxp;
    global Fishingxpleft;
    global Mininglvl;
    global Miningxpremain;
    global Miningxpgain;
    global Miningcurxp;
    global Miningxpleft;
    global Smithinglvl;
    global Smithingxpremain;
    global Smithingxpgain;
    global Smithingcurxp;
    global Smithingxpleft;
    global Thievinglvl;
    global Thievingxpremain;
    global Thievingxpgain;
    global Thievingcurxp;
    global Thievingxpleft;
    global ttllvl;
    acc1g = 0;
    acc1m = 'Open';
    acc2g = 0;
    acc2m = 'Open';
    acc3g = 0;
    acc3m = 'Open';
    acc4g = 0;
    acc4m = 'Open';
    acc5g = 0;
    acc5m = 'Open';
    cost = '--';
    cost1 = '--';
    gcho = '--';
    echo = '--';
    e2cho = '--';
    e1 = '--';
    dmgnpc = 0;
    ls1 = 0;
    killcount = 0;
    ls2 = 0;
    la1 = 0;
    la2 = 0;
    hp = 200;
    orighp = 200;
    armtype = 'No';
    swordtype = 'Your';
    skind = 'hand';
    buyword1 = 'hi';
    buyword2 = 'hi';
    curlvl = 1;
    aan = 'a';
    bankgold = 0;
    destination1 = SAVE_GAME_FILES();
    destination2 = SAVE_GAME_FILES();
    swordchoice = 'hi';
    swordchoice2 = 'hi';
    swordchoice3 = 'hi';
    swordexist = 'hi';
    sprice = 0;
    armchoice = 'hi';
    armchoice2 = 'Armor';
    aprice = 0;
    playerxp = 0;
    xpuntil = 500;
    origxp = 500;
    money = 500;
    key = 0;
    damage = 0;
    dr =  0;
    gmail = 0;
    hbone = 0;
    dhide = 0;
    rtab = 0;
    food = 0;
    rfood = 0;
    bait = 0;
    ea = 'None';
    potion = 0;
    ingot = 0;
    seed = 0;
    bow = 0;
    fur = 0;
    gem = 0;
    log = 0;
    ore = 0;
    morb = 0;
    arm1 = 0;
    arm2 = 0;
    arm3 = 0;
    arm4 = 0;
    arm5 = 0;
    arm6 = 0;
    arm7 = 0;
    arm8 = 0;
    arm9 = 0;
    arm10 = 0;
    arm11 = 0;
    arm12 = 0;
    ma1 = 0;
    ma2 = 0;
    ma3 = 0;
    ma4 = 0;
    ma5 = 0;
    ma6 = 0;
    ma7 = 0;
    ma8 = 0;
    ma9 = 0;
    ma10 = 0;
    ms1 = 0;
    ms2 = 0;
    ms3 = 0;
    ms4 = 0;
    ms5 = 0;
    ms6 = 0;
    ms7 = 0;
    ms8 = 0;
    ms9 = 0;
    ms10 = 0;
    sword1 = 0;
    sword2 = 0;
    sword3 = 0;
    sword4 = 0;
    sword5 = 0;
    sword6 = 0;
    sword7 = 0;
    sword8 = 0;
    sword9 = 0;
    sword10 = 0;
    sword11 = 0;
    sword12 = 0;
    axxx = 0;
    pgmail = 300;
    phbone = 550;
    pdhide = 750;
    prtab = 250;
    ppotion = 200;
    pfood = 100;
    pingot = 473;
    pseed = 150;
    prfood = 100;
    pbait = 2;
    pfur = 200;
    pore = 500;
    plog = 275;
    pgem = 1000;
    pbow = 713;
    pmorb = 15000;
    Woodcuttinglvl = 1;
    Woodcuttingxpremain = 100;
    Woodcuttingxpgain = 38;
    Woodcuttingcurxp = 0;
    Woodcuttingxpleft = 100;
    Cooklvl = 1;
    Cookxpremain = 100;
    Cookxpgain = 41;
    Cookcurxp = 0;
    Cookxpleft = 100;
    Fishinglvl = 1;
    Fishingxpremain = 100;
    Fishingxpgain = 30;
    Fishingcurxp = 0;
    Fishingxpleft = 100;
    Mininglvl = 1;
    Miningxpremain = 100;
    Miningxpgain = 35;
    Miningcurxp = 0;
    Miningxpleft = 100;
    Smithinglvl = 1;
    Smithingxpremain = 100;
    Smithingxpgain = 33;
    Smithingcurxp = 0;
    Smithingxpleft = 100;
    Thievinglvl = 1;
    Thievingxpremain = 100;
    Thievingxpgain = 36;
    Thievingcurxp = 0;
    Thievingxpleft = 100;
    ttllvl = 13;
    #SAVE_GAME_FILES();
    MENU()
def MENU():
    global ttllvl;
    ttllvl = Woodcuttinglvl + Cooklvl + Fishinglvl +Mininglvl + Smithinglvl+ Thievinglvl;
    os.system('cls');
    print('***************************');
    print('*What would you like to do?*');
    print('***************************');
    print('* 1) Wander Gielinor       *');
    print('*                          *');
    print('* 2) Weapon Shop           *');
    print('*                          *');
    print('* 3) Armor Shop            *');
    print('*                          *');
    print('* 4) Legends Store         *');
    print('*                          *');
    print('* 5) Trading Post          *');
    print('*                          *');
    print('* 6) Smuggler              *');
    print('*                          *');
    print('* 7) The Stronghold        *');
    print('*                          *');
    print('* 8) Skill Plot            *');
    print('*                          *');
    print('* 9) RealmBank             *');
    print('*                          *');
    print('*97) Your Inventory        *');
    print('***************************');
    print();
    print();
    print('****************************************');
    print('   Currently logged in as',username1);
    print('****************************************');
    print('*98) Settings                          *');
    print('*99) Log out                           *');
    print('****************************************');
    try:
        x1 = int(input());
        if x1 == 1:
            picknpc();
        elif x1 == 2:
            weaponstore();
        elif x1 == 3:
            Armorstore();
        elif x1 == 4:
            legendstore();
        elif x1 == 5:
            gstore();
        elif x1 == 6:
            smuggler();
        elif x1 == 7:
            STR_PIC();
        elif x1 == 8:
            skillplot();
        elif x1 == 9:
            BANK();
        elif x1 == 97:
            checkitems();
        elif x1 == 98:
            settings();
        elif x1 == 99:
            entergame();
        else:
            MENU();
    except ValueError:
        MENU();
def REST():
    global hp
    os.system('cls');
    hp = orighp;
    print('You are now at full health and well rested!');
    time.sleep(1.5);
def BANK():
    global destination1;
    global bankgold
    destination1 = BANK()
    os.system('cls')
    print("Welcome to RealmBank!");
    print("Here are your accounts which you can store up to 1,000,000,000 (1B) gold into each.");
    print();
    print('*******************************');
    print(' You have',money,'gold.');
    print('*******************************');
    print('      Account 1:',acc1m);
    print('         - Gold:',acc1g);
    print();
    print('      Account 2:',acc2m);
    print('         - Gold:',acc2g);
    print();
    print('      Account 3:',acc3m);
    print('         - Gold:',acc3g);
    print();
    print('      Account 4:',acc4m);
    print('         - Gold:',acc4g);
    print();
    print('      Account 5:',acc5m);
    print('         - Gold:',acc5g);
    print('*******************************');
    print();
    print('Type "exit" to exit.');
    a5 = input('Access account number: ');
    if a5 == 1:
        bankgold = acc1g;
        bankfull = acc1m;
    depositwithdraw();
entergame();
